// Store-owned delivery policy (spec-amend-s4 section 6.1).
//
// "Delivery is not caller optional" (R2-6). Whether an event produces an outbox row
// is a property of the EVENT TYPE, decided here, and no caller flag can force or
// suppress it - there is deliberately no --deliver/--no-deliver switch on any verb.
//
// S2 owns this map as the tested store contract for the WHOLE event vocabulary, but
// S2 only EMITS outbox rows from its own verbs (complete/fail/cancel) - ruling
// RISK#2 (NARROW). Wiring S1's nonterminal deliverable events (progress, blocked,
// unblocked, waiting_firstmate, needs_human, rework) into appendEvent is deferred to
// follow-up cp-nonterminal-delivery, so this file is deliberately ahead of its call
// sites. That is intentional and is what makes the map independently testable now:
// classify() is total over the event vocabulary today, and the deferred slice only
// has to start CALLING it, never to redefine it.

// Events FirstMate must see to preserve operational truth (spec section 6.1).
// `cancelled` is deliverable as generated by the COORDINATOR (S2's cancel verb).
// The spec's "if generated by coordinator rather than FirstMate itself" carve-out
// bites only once FirstMate can author its own cancellation, which no slice through
// S2 can do; when that arrives it is a producer-aware refinement of this entry, not
// a change to the rest of the map.
export const DELIVERABLE_EVENT_TYPES = Object.freeze(new Set([
  'progress',
  'blocked',
  'unblocked',
  'waiting_firstmate',
  'needs_human',
  'rework',
  'completed',
  'failed',
  'cancelled'
]));

// Local/audit-only events. They are durable in task_events and visible through the
// snapshot/anomaly projections, but they are not pushed to the FirstMate consumer
// and create no outbox row "unless a later spec explicitly makes them visible".
export const AUDIT_ONLY_EVENT_TYPES = Object.freeze(new Set([
  'spawn_intent',
  'spawned',
  'running_verified',
  'cleanup_started',
  'cleaned',
  'archived',
  'anomaly',
  'created',
  'identity_lost'
]));

// True when the store MUST create an outbox row for this event type.
// Unknown types are a programming error, not a silent no-delivery default: an event
// type added to the DDL without a delivery decision must fail loudly here rather
// than quietly never reaching FirstMate.
export function isDeliverable(eventType) {
  if (DELIVERABLE_EVENT_TYPES.has(eventType)) return true;
  if (AUDIT_ONLY_EVENT_TYPES.has(eventType)) return false;
  throw new Error(
    `delivery policy has no entry for event type '${eventType}'; ` +
    'every event type must be classified deliverable or audit-only (spec section 6.1)'
  );
}

// The whole map as data, for the contract test and for any later projection that
// needs to reason about delivery without calling isDeliverable per type.
export function deliveryPolicyMap() {
  const map = new Map();
  for (const t of DELIVERABLE_EVENT_TYPES) map.set(t, 'deliver');
  for (const t of AUDIT_ONLY_EVENT_TYPES) map.set(t, 'audit_only');
  return map;
}
